server:
  port: 8082

spring:
  application:
    name: enricher-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: enricher-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
